# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiuCalculatorPro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiuCalculatorPro
#  pod 'MBProgressHUD'
  pod 'GDTMobSDK'
  pod 'BaiduMobStatCodeless'
  pod 'SDAutoLayout'
  pod 'FMDB'
  pod 'SXAlertView'
  pod 'SVProgressHUD'
  target 'MiuCalculatorProTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiuCalculatorProUITests' do
    # Pods for testing
  end

end
